site_name: Tiger's Digital Garden
docs_dir: notes
theme:
  name: material
  favicon: images/favicon.png
markdown_extensions:
  - attr_list
extra:
  analytics:
    provider: google
    property: G-XZ41DZYYBH
