site_name: Tiger's Digital Garden
docs_dir: notes
theme:
  name: material
  favicon: images/favicon.webp
markdown_extensions:
  - attr_list
  - md_in_html
extra:
  analytics:
    provider: google
    property: G-XZ41DZYYBH
extra_css:
  - stylesheets/extra.css
