site_name: Tiger's Digital Garden
docs_dir: notes
theme:
  name: material
  favicon: images/favicon.webp
markdown_extensions:
  - attr_list
  - md_in_html
  # requires python-markdown extension mdx_truly_sane_lists
  # this extension allows indent by using 2 spaces
  # needed because mdformat formats nested list to use 2 spaces
  - mdx_truly_sane_lists
extra:
  analytics:
    provider: google
    property: G-XZ41DZYYBH
extra_css:
  - stylesheets/extra.css
